#!/bin/sh

name=`./build | tail -1`
tar=gen/dist/*.tar.gz
tarname=`basename $tar`
scp $tar im:.

ssh im <<EOF
  tar xfz $tarname
  [ -x /home/immunity/app/bin/stop ] && /home/immunity/app/bin/stop
  rm /home/immunity/app
  ln -s /home/immunity/$name /home/immunity/app
  /home/immunity/app/bin/start
  rm /home/immunity/*.tar.gz
EOF
